version: '3.7'
services:
  neo4j:
    image: neo4j:community
    container_name: neo4j_mutual_friends
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./docker/neo4j/conf:/conf
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/import:/import
      - ./docker/neo4j/logs:/logs
      - ./docker/neo4j/plugins:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G